services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://user:password@db/bookstore
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookstore

volumes:
  postgres_data:
